# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bryce/Documents/PerPer/Graficadora

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bryce/Documents/PerPer/Graficadora

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryce/Documents/PerPer/Graficadora/CMakeFiles /home/bryce/Documents/PerPer/Graficadora/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryce/Documents/PerPer/Graficadora/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Graficadora

# Build rule for target.
Graficadora: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Graficadora
.PHONY : Graficadora

# fast build rule for target.
Graficadora/fast:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/build
.PHONY : Graficadora/fast

#=============================================================================
# Target rules for targets named Graficadora_autogen

# Build rule for target.
Graficadora_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Graficadora_autogen
.PHONY : Graficadora_autogen

# fast build rule for target.
Graficadora_autogen/fast:
	$(MAKE) -f CMakeFiles/Graficadora_autogen.dir/build.make CMakeFiles/Graficadora_autogen.dir/build
.PHONY : Graficadora_autogen/fast

Graficadora_autogen/mocs_compilation.o: Graficadora_autogen/mocs_compilation.cpp.o

.PHONY : Graficadora_autogen/mocs_compilation.o

# target to build an object file
Graficadora_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/Graficadora_autogen/mocs_compilation.cpp.o
.PHONY : Graficadora_autogen/mocs_compilation.cpp.o

Graficadora_autogen/mocs_compilation.i: Graficadora_autogen/mocs_compilation.cpp.i

.PHONY : Graficadora_autogen/mocs_compilation.i

# target to preprocess a source file
Graficadora_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/Graficadora_autogen/mocs_compilation.cpp.i
.PHONY : Graficadora_autogen/mocs_compilation.cpp.i

Graficadora_autogen/mocs_compilation.s: Graficadora_autogen/mocs_compilation.cpp.s

.PHONY : Graficadora_autogen/mocs_compilation.s

# target to generate assembly for a file
Graficadora_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/Graficadora_autogen/mocs_compilation.cpp.s
.PHONY : Graficadora_autogen/mocs_compilation.cpp.s

analizador.o: analizador.cpp.o

.PHONY : analizador.o

# target to build an object file
analizador.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/analizador.cpp.o
.PHONY : analizador.cpp.o

analizador.i: analizador.cpp.i

.PHONY : analizador.i

# target to preprocess a source file
analizador.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/analizador.cpp.i
.PHONY : analizador.cpp.i

analizador.s: analizador.cpp.s

.PHONY : analizador.s

# target to generate assembly for a file
analizador.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/analizador.cpp.s
.PHONY : analizador.cpp.s

arbol.o: arbol.cpp.o

.PHONY : arbol.o

# target to build an object file
arbol.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/arbol.cpp.o
.PHONY : arbol.cpp.o

arbol.i: arbol.cpp.i

.PHONY : arbol.i

# target to preprocess a source file
arbol.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/arbol.cpp.i
.PHONY : arbol.cpp.i

arbol.s: arbol.cpp.s

.PHONY : arbol.s

# target to generate assembly for a file
arbol.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/arbol.cpp.s
.PHONY : arbol.cpp.s

b_node.o: b_node.cpp.o

.PHONY : b_node.o

# target to build an object file
b_node.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/b_node.cpp.o
.PHONY : b_node.cpp.o

b_node.i: b_node.cpp.i

.PHONY : b_node.i

# target to preprocess a source file
b_node.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/b_node.cpp.i
.PHONY : b_node.cpp.i

b_node.s: b_node.cpp.s

.PHONY : b_node.s

# target to generate assembly for a file
b_node.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/b_node.cpp.s
.PHONY : b_node.cpp.s

funciones.o: funciones.cpp.o

.PHONY : funciones.o

# target to build an object file
funciones.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/funciones.cpp.o
.PHONY : funciones.cpp.o

funciones.i: funciones.cpp.i

.PHONY : funciones.i

# target to preprocess a source file
funciones.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/funciones.cpp.i
.PHONY : funciones.cpp.i

funciones.s: funciones.cpp.s

.PHONY : funciones.s

# target to generate assembly for a file
funciones.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/funciones.cpp.s
.PHONY : funciones.cpp.s

graficadora.o: graficadora.cpp.o

.PHONY : graficadora.o

# target to build an object file
graficadora.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/graficadora.cpp.o
.PHONY : graficadora.cpp.o

graficadora.i: graficadora.cpp.i

.PHONY : graficadora.i

# target to preprocess a source file
graficadora.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/graficadora.cpp.i
.PHONY : graficadora.cpp.i

graficadora.s: graficadora.cpp.s

.PHONY : graficadora.s

# target to generate assembly for a file
graficadora.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/graficadora.cpp.s
.PHONY : graficadora.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/main.cpp.s
.PHONY : main.cpp.s

mapa.o: mapa.cpp.o

.PHONY : mapa.o

# target to build an object file
mapa.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/mapa.cpp.o
.PHONY : mapa.cpp.o

mapa.i: mapa.cpp.i

.PHONY : mapa.i

# target to preprocess a source file
mapa.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/mapa.cpp.i
.PHONY : mapa.cpp.i

mapa.s: mapa.cpp.s

.PHONY : mapa.s

# target to generate assembly for a file
mapa.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/mapa.cpp.s
.PHONY : mapa.cpp.s

nodo_num.o: nodo_num.cpp.o

.PHONY : nodo_num.o

# target to build an object file
nodo_num.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/nodo_num.cpp.o
.PHONY : nodo_num.cpp.o

nodo_num.i: nodo_num.cpp.i

.PHONY : nodo_num.i

# target to preprocess a source file
nodo_num.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/nodo_num.cpp.i
.PHONY : nodo_num.cpp.i

nodo_num.s: nodo_num.cpp.s

.PHONY : nodo_num.s

# target to generate assembly for a file
nodo_num.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/nodo_num.cpp.s
.PHONY : nodo_num.cpp.s

nodo_op.o: nodo_op.cpp.o

.PHONY : nodo_op.o

# target to build an object file
nodo_op.cpp.o:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/nodo_op.cpp.o
.PHONY : nodo_op.cpp.o

nodo_op.i: nodo_op.cpp.i

.PHONY : nodo_op.i

# target to preprocess a source file
nodo_op.cpp.i:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/nodo_op.cpp.i
.PHONY : nodo_op.cpp.i

nodo_op.s: nodo_op.cpp.s

.PHONY : nodo_op.s

# target to generate assembly for a file
nodo_op.cpp.s:
	$(MAKE) -f CMakeFiles/Graficadora.dir/build.make CMakeFiles/Graficadora.dir/nodo_op.cpp.s
.PHONY : nodo_op.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Graficadora"
	@echo "... edit_cache"
	@echo "... Graficadora_autogen"
	@echo "... Graficadora_autogen/mocs_compilation.o"
	@echo "... Graficadora_autogen/mocs_compilation.i"
	@echo "... Graficadora_autogen/mocs_compilation.s"
	@echo "... analizador.o"
	@echo "... analizador.i"
	@echo "... analizador.s"
	@echo "... arbol.o"
	@echo "... arbol.i"
	@echo "... arbol.s"
	@echo "... b_node.o"
	@echo "... b_node.i"
	@echo "... b_node.s"
	@echo "... funciones.o"
	@echo "... funciones.i"
	@echo "... funciones.s"
	@echo "... graficadora.o"
	@echo "... graficadora.i"
	@echo "... graficadora.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mapa.o"
	@echo "... mapa.i"
	@echo "... mapa.s"
	@echo "... nodo_num.o"
	@echo "... nodo_num.i"
	@echo "... nodo_num.s"
	@echo "... nodo_op.o"
	@echo "... nodo_op.i"
	@echo "... nodo_op.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

